image: microsoft/dotnet:2.1-aspnetcore-runtime


stages:
    - build

before_script:
    - "cd home-panel-app"
    - "dotnet restore"
    - "npm install"

build:
    stage: build
    script:
        - "dotnet publish -c Release -r linux-arm"
