image: microsoft/aspnetcore-build:latest

cache:
    paths:
    - node_modules/

stages:
    - build

before_script:
    - npm install
    - "cd home-panel-app"

build:
    stage: build
    script:
        - "dotnet publish -c Release -r linux-arm"
