image: microsoft/dotnet:latest

services:
    - node

stages:
    - build

before_script:
    - "cd home-panel-app"

build:
    stage: build
    script:
        - "dotnet publish -c Release -r linux-arm"
