image: microsoft/dotnet:latest

stages:
    - build

before_script:
    - "cd home-panel-app"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet publish -c Release -r linux-arm"
