image: microsoft/dotnet:2.1-sdk

stages:
    - build

before_script:
    - apt-get update
    - apt-get install -y wget
    - apt-get install -y gnupg2
    - wget -qO- https://deb.nodesource.com/setup_6.x | bash -
    - apt-get install -y build-essential nodejs
    - "cd home-panel-app"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet publish -c Release -r linux-arm"
